# Generated by Django 3.2 on 2025-09-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagepool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='localCustompool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localpoolname', models.CharField(max_length=100, unique=True)),
                ('localpoolpath', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'localCustompool',
            },
        ),
    ]
